################################################################################
# SQL code styling tool
# reference data
#
# Author: Daniel Contractor
# Updated: Simon Anastasiadis
################################################################################

ref_data = list(
  ## keyword list ----
  keywords_list = c(
    "SELECT",
    "FROM",
    "WHERE",
    "INNER JOIN",
    "OUTER JOIN",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "AND",
    "OR",
    "BULK",
    "UPDATE",
    "DELETE",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "WITH"
  ),
  
  ## new keywords ----
  new_keywords = c(
    "ADD CONSTRAINT",
    "ANY",
    "ASC",
    "BACKUP DATABASE",
    "BETWEEN",
    "CHECK",
    "CONSTRAINT",
    "CREATE DATABASE",
    "CREATE INDEX",
    "CREATE OR REPLACE VIEW",
    "CREATE TABLE",
    "CREATE PROCEDURE",
    "CREATE UNIQUE INDEX",
    "CREATE VIEW",
    "DATABASE",
    "DEFAULT",
    "DROP CONSTRAINT",
    "DROP DATABASE",
    "DROP DEFAULT",
    "DROP INDEX",
    "DROP VIEW",
    "EXEC",
    "FOREIGN KEY",
    "FULL OUTER JOIN",
    "GO",
    "GROUP BY",
    "HAVING",
    "INSERT INTO",
    "INSERT INTO SELECT",
    "LEFT JOIN",
    "LIMIT",
    "PRIMARY KEY",
    "PROCEDURE",
    "RIGHT JOIN",
    "ROWNUM",
    "SELECT DISTINCT",
    "SELECT INTO",
    "SELECT TOP",
    "SET",
    "TOP",
    "TRUNCATE TABLE",
    "UNION",
    "UNIQUE",
    "VALUES",
    "VIEW",
    "ON",
    "REBUILD",
    "JOIN",
    "INTO"
  ),
  
  ## join keywords ----
  join_keywords = c(
    "JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "INNER JOIN",
    "OUTER JOIN",
    "FULL JOIN",
    "LEFT OUTER JOIN",
    "RIGHT OUTER JOIN",
    "CROSS JOIN",
    "NATURAL JOIN"
  ),
  
  ## sql functions ----
  sql_functions = c(
    "ABS",
    "ASCII",
    "AVG",
    "CAST",
    "CASE",
    "CEIL",
    "CEILING",
    "CHAR",
    "CHARINDEX",
    "CONCAT",
    "CONVERT",
    "COUNT",
    "CURRENT_TIMESTAMP",
    "CURRENT_USER",
    "CURDATE",
    "DATEDIFF",
    "DATENAME",
    "DATEPART",
    "DATEADD",
    "DAY",
    "DATALENGTH",
    "EXTRACT",
    "FLOOR",
    "GETDATE",
    "GETUTCDATE",
    "IF",
    "ISDATE",
    "ISNULL",
    "ISNUMERIC",
    "LAG",
    "LEAD",
    "LEFT",
    "LEN",
    "LOWER",
    "LTRIM",
    "MAX",
    "MIN",
    "MOD",
    "MONTH",
    "NCHAR",
    "NOW",
    "NULLIF",
    "OBJECT_ID",
    "OVER",
    "PATINDEX",
    "POWER",
    "RAND",
    "REPLACE",
    "RIGHT",
    "ROUND",
    "RTRIM",
    "SESSION_USER",
    "SESSIONPROPERTY",
    "SIGN",
    "SPACE",
    "STR",
    "STUFF",
    "SUBSTRING",
    "SUM",
    "SYSTEM_USER",
    "TRIM",
    "TRY_CAST",
    "TRY_CONVERT",
    "TOP",
    "UPPER",
    "USER_NAME",
    "YEAR",
    "VARCHAR",
    "DATEFROMPARTS",
    "EOMONTH",
    "in",
    "IN",
    "COALESCE",
    "DATEADD",
    "OVER",
    "IIF",
    "RANK",
    "ROW_NUMBER"
  ),
  
  ## capitalisation keywords ----
  capitalisation_keywords = c(
    "ALL",
    "AS",
    "BY",
    "DESC",
    "DISTINCT",
    "ELSE",
    "END",
    "EXCEPT",
    "EXISTS",
    "FULL",
    "GROUP",
    "ILIKE",
    "INNER",
    "INSERT",
    "INTERSECT",
    "IS",
    "LIKE",
    "NOT",
    "NULL",
    "OFFSET",
    "ORDER",
    "OUTER",
    "PARTITION",
    "TABLE",
    "THEN",
    "WHEN"
  )
  
)
